using System.Windows;
using SmartScreen.Application.Abstractions;

namespace SmartScreen.App.Services;

public static class LocalizationResourceService
{
    private const string ResourcePrefix = "Loc.";

    private static readonly IReadOnlyDictionary<string, string> BuiltInFallback = new Dictionary<string, string>
    {
        ["app.title"] = "SmartScreen",
        ["app.subtitle"] = "центр захоплень",
        ["app.alreadyRunning"] = "SmartScreen вже запущено. Перевір іконку в системному треї або закрий попередній екземпляр.",
        ["app.unexpectedError"] = "Сталася неочікувана помилка. Деталі записано в logs/app.log.",
        ["action.captureRegion"] = "Скріншот області",
        ["action.captureFullScreen"] = "Скріншот всього екрана",
        ["action.captureActiveWindow"] = "Скріншот активного вікна",
        ["action.captureMonitor"] = "Скріншот монітора",
        ["action.captureDelayed"] = "Скріншот із затримкою",
        ["action.askAi"] = "Запитати AI",
        ["tray.openSmartScreen"] = "Відкрити SmartScreen",
        ["tray.exit"] = "Вийти",
        ["tray.readyTitle"] = "SmartScreen працює",
        ["tray.readyMessage"] = "Натисни Ctrl+Shift+S або відкрий меню іконки в треї.",
        ["main.captureSection"] = "Захоплення",
        ["main.region"] = "Область",
        ["main.fullScreen"] = "Весь екран",
        ["main.activeWindow"] = "Активне вікно",
        ["main.monitor"] = "Монітор",
        ["main.delay"] = "Затримка",
        ["main.askAi"] = "Запитати AI",
        ["main.settings"] = "Налаштування",
        ["main.primaryHotkey"] = "Основний хоткей",
        ["main.workspace"] = "Робочий центр",
        ["main.inTray"] = "у треї",
        ["main.openScreenshotsFolder"] = "Відкрити папку скріншотів",
        ["main.currentScreenshot"] = "Поточний скріншот",
        ["main.waitingCapture"] = "Очікує захоплення",
        ["main.noScreenshot"] = "Немає скріншоту",
        ["main.captureRegionTooltip"] = "Скріншот області",
        ["main.captureActiveWindowTooltip"] = "Скріншот активного вікна",
        ["main.captureMonitorTooltip"] = "Скріншот монітора",
        ["main.captureDelayedTooltip"] = "Скріншот із затримкою",
        ["main.askCurrentScreenshotTooltip"] = "Запитати AI про поточний скріншот",
        ["main.window"] = "Вікно",
        ["main.timer"] = "Таймер",
        ["main.recentScreenshots"] = "Останні скріншоти",
        ["main.sessionSuffix"] = "у сесії",
        ["main.emptySession"] = "Історія сесії порожня",
        ["main.emptySessionHint"] = "Після захоплення тут з'явиться прев'ю.",
        ["main.activeAiRoute"] = "Активний AI-маршрут",
        ["main.userActionOnly"] = "лише за дією користувача",
        ["main.workflow"] = "Сценарій",
        ["main.workflowStepCapture"] = "1. Захоплення",
        ["main.workflowStepOutput"] = "2. Буфер або файл",
        ["main.workflowStepTools"] = "3. Редактор, AI, папка",
        ["main.aiNotConfigured"] = "AI не налаштовано",
        ["main.openSettingsHint"] = "Відкрий налаштування",
        ["main.noActiveRoute"] = "Немає активного маршруту",
        ["main.error.captureFullScreen"] = "Не вдалося зробити скріншот всього екрана",
        ["main.error.captureRegion"] = "Не вдалося зробити скріншот області",
        ["main.error.captureActiveWindow"] = "Не вдалося зробити скріншот активного вікна",
        ["main.error.captureMonitor"] = "Не вдалося зробити скріншот монітора",
        ["main.error.captureDelayed"] = "Не вдалося зробити скріншот із затримкою",
        ["main.status.actionCancelled"] = "Дію скасовано",
        ["main.status.errorWithLogs"] = "{0}. Деталі записано в logs/app.log.",
        ["main.status.captureFirst"] = "Спочатку зроби скріншот",
        ["main.status.openScreenshotsFolderFailed"] = "Не вдалося відкрити папку скріншотів",
        ["main.workflowAction.manual"] = "manual",
        ["main.workflowAction.clipboard"] = "clipboard",
        ["main.workflowAction.file"] = "file",
        ["main.workflowAction.quickMenu"] = "quick menu",
        ["main.workflowAction.editor"] = "editor",
        ["overlay.selectRegionHint"] = "Виділи область мишкою. Esc — скасувати.",
        ["capture.source.fullScreen"] = "Весь екран",
        ["capture.source.activeWindow"] = "Активне вікно",
        ["capture.source.primaryMonitor"] = "Основний монітор",
        ["capture.source.monitor"] = "Монітор {0}",
        ["capture.source.selectedRegion"] = "Вибрана область",
        ["capture.source.savedScreenshot"] = "Збережений скріншот",
        ["capture.source.editedScreenshot"] = "Відредагований скріншот",
        ["capture.source.editedCroppedScreenshot"] = "Відредагований обрізаний скріншот",
        ["capture.status.waitingRegion"] = "Очікую виділення області...",
        ["capture.status.regionCancelled"] = "Виділення області скасовано",
        ["capture.status.creatingFullScreen"] = "Створюю скріншот всього екрана...",
        ["capture.status.creatingActiveWindow"] = "Створюю скріншот активного вікна...",
        ["capture.status.creatingMonitor"] = "Створюю скріншот монітора #{0}...",
        ["capture.status.delayCountdown"] = "Скріншот через {0} сек...",
        ["capture.status.alreadyRunning"] = "Сценарій скріншота вже виконується",
        ["capture.status.actionFailedWithLogs"] = "Не вдалося виконати дію. Деталі записано в logs/app.log.",
        ["capture.status.ready"] = "Скріншот готовий: {0}x{1}",
        ["capture.status.readyWithActions"] = "Скріншот готовий: {0}x{1}; {2}",
        ["capture.completed.clipboard"] = "буфер",
        ["capture.completed.clipboardUnavailable"] = "буфер недоступний",
        ["capture.completed.file"] = "файл {0}",
        ["settings.title"] = "Налаштування",
        ["settings.subtitle"] = "Керування скріншотами, AI-маршрутами, prompt-шаблонами та глобальними клавішами",
        ["settings.save"] = "Зберегти",
        ["settings.sections"] = "Розділи",
        ["settings.sectionsHint"] = "Усе важливе без ручного JSON",
        ["settings.section.general.title"] = "Загальні",
        ["settings.section.general.description"] = "запуск, portable, папки",
        ["settings.section.screenshots.title"] = "Скріншоти",
        ["settings.section.screenshots.description"] = "формат, файл, pipeline",
        ["settings.section.editor.title"] = "Редактор",
        ["settings.section.editor.description"] = "колір, товщина, текст",
        ["settings.section.ai.title"] = "AI-провайдери",
        ["settings.section.ai.description"] = "маршрути, ключі, моделі",
        ["settings.section.prompts.title"] = "Prompt-шаблони",
        ["settings.section.prompts.description"] = "дії для AI-аналізу",
        ["settings.section.hotkeys.title"] = "Гарячі клавіші",
        ["settings.section.hotkeys.description"] = "глобальні комбінації",
        ["settings.section.interface.title"] = "Інтерфейс",
        ["settings.section.interface.description"] = "тема та акцент",
        ["settings.section.languages.title"] = "Мови",
        ["settings.section.languages.description"] = "локалізація UI",
        ["settings.section.security.title"] = "Безпека",
        ["settings.section.security.description"] = "приватність і секрети",
        ["settings.section.logs.title"] = "Логи",
        ["settings.section.logs.description"] = "діагностика і конфіги",
        ["settings.promptEditing"] = "Редагування prompt",
        ["settings.logsAndFiles"] = "Логи та файли",
        ["settings.add"] = "Додати",
        ["settings.delete"] = "Видалити",
        ["settings.restore"] = "Відновити",
        ["settings.open"] = "Відкрити",
        ["settings.openConfig"] = "Відкрити config",
        ["settings.enabled"] = "Увімкнено",
        ["settings.test"] = "Тест",
        ["settings.field.name"] = "Назва",
        ["settings.field.type"] = "Тип",
        ["settings.field.category"] = "Категорія",
        ["settings.general.description"] = "SmartScreen залишається tray-first утилітою: головне вікно відкривається тоді, коли треба щось налаштувати.",
        ["settings.general.startMinimized"] = "Запускати згорнуто в трей",
        ["settings.general.closeToTray"] = "Закривати вікно в трей",
        ["settings.general.firstRunCompleted"] = "Перший запуск завершено",
        ["settings.general.portableStorage"] = "Portable storage",
        ["settings.general.config"] = "Config",
        ["settings.screenshots.description"] = "Формат, папка, назва файлу та дії після захоплення.",
        ["settings.screenshots.defaultMode"] = "Режим за замовчуванням",
        ["settings.screenshots.format"] = "Формат",
        ["settings.screenshots.monitor"] = "Монітор",
        ["settings.screenshots.saveFolder"] = "Папка збереження",
        ["settings.screenshots.jpegQuality"] = "JPG якість",
        ["settings.screenshots.delaySeconds"] = "Затримка, сек",
        ["settings.screenshots.fileNameTemplate"] = "Шаблон імені файлу",
        ["settings.screenshots.pipeline"] = "Pipeline після скріншоту",
        ["settings.workflow.copy"] = "Копія",
        ["settings.workflow.editor"] = "Редактор",
        ["settings.workflow.ask"] = "Запит",
        ["settings.workflow.silentFile"] = "Тихий файл",
        ["settings.workflow.clipboard"] = "Буфер обміну",
        ["settings.workflow.saveFile"] = "Зберегти файл",
        ["settings.workflow.quickMenu"] = "Швидке меню",
        ["settings.workflow.openEditor"] = "Відкрити редактор",
        ["settings.workflow.askAi"] = "Запитати AI",
        ["settings.editor.description"] = "Базові параметри інструментів для позначок на скріншоті.",
        ["settings.editor.color"] = "Колір",
        ["settings.editor.thickness"] = "Товщина",
        ["settings.editor.textSize"] = "Розмір тексту",
        ["settings.editor.highlighterOpacity"] = "Маркер opacity",
        ["settings.ai.activeRoute"] = "Активний маршрут для AI-відповідей",
        ["settings.ai.endpoint"] = "Endpoint",
        ["settings.ai.timeoutSeconds"] = "Timeout, sec",
        ["settings.ai.model"] = "Model",
        ["settings.ai.apiKey"] = "API key",
        ["settings.ai.envVar"] = "Env var",
        ["settings.ai.systemPrompt"] = "System prompt",
        ["settings.prompts.templatesSuffix"] = "шаблонів",
        ["settings.prompts.categories"] = "Категорії",
        ["settings.prompts.addCategory"] = "Додати категорію",
        ["settings.prompts.deleteCategory"] = "Видалити власну категорію",
        ["settings.prompts.savedToConfig"] = "Зміни зберігаються у config/prompts.json",
        ["settings.prompts.categoryName"] = "Назва категорії",
        ["settings.prompts.system"] = "Системна",
        ["settings.hotkeys.activeSuffix"] = "активних комбінацій",
        ["settings.hotkeys.validate"] = "Перевірити",
        ["settings.hotkeys.defaults"] = "Стандартні",
        ["settings.hotkeys.gesture"] = "Комбінація",
        ["settings.hotkeys.quickAiPrompt"] = "AI prompt для швидкої дії",
        ["settings.interface.description"] = "Тема, accent color і поведінка вікон.",
        ["settings.interface.theme"] = "Тема",
        ["settings.interface.accentColor"] = "Accent color",
        ["settings.languages.description"] = "Файли локалізації лежать поруч із застосунком, тому нові мови можна додавати через JSON.",
        ["settings.languages.uiLanguage"] = "Мова UI",
        ["settings.languages.folder"] = "Папка локалізації",
        ["settings.security.description"] = "AI-запит виконується тільки після явної дії користувача, ключі зберігаються окремо від git-конфігів.",
        ["settings.security.confirmBeforeSending"] = "Надсилати скріншоти до AI тільки після підтвердження користувача",
        ["settings.security.secrets"] = "Secrets",
        ["settings.logs.description"] = "Швидкий доступ до portable-директорій для діагностики.",
        ["settings.logs.logs"] = "Logs",
        ["settings.logs.screenshots"] = "Screenshots",
        ["settings.logs.themes"] = "Themes",
        ["settings.status.initial"] = "Налаштування",
        ["settings.status.loaded"] = "Налаштування завантажено",
        ["settings.status.saved"] = "Налаштування збережено, hotkeys перереєстровано",
        ["settings.status.checkingAi"] = "Перевіряю підключення...",
        ["settings.status.aiConnected"] = "Підключення працює",
        ["settings.status.aiConnectionFailed"] = "Підключення не вдалося перевірити",
        ["settings.status.hotkeysRestored"] = "Стандартні hotkeys відновлено. Натисни «Зберегти», щоб застосувати",
        ["settings.status.hotkeysValid"] = "Hotkeys валідні",
        ["settings.status.promptAdded"] = "Prompt додано. Натисни «Зберегти», щоб записати",
        ["settings.status.providerAdded"] = "AI-провайдера додано. Заповни endpoint, model і ключ",
        ["settings.status.providerDeleted"] = "AI-провайдера видалено. Натисни «Зберегти», щоб застосувати",
        ["settings.status.categoryAdded"] = "Категорію prompt-ів додано. Перейменуй і натисни «Зберегти»",
        ["settings.status.categoryDeleted"] = "Категорію видалено, її prompt-и перенесено в іншу категорію",
        ["settings.status.promptDeleted"] = "Prompt видалено. Стандартні можна повернути кнопкою «Відновити»",
        ["settings.status.promptsRestored"] = "Стандартні prompt-шаблони відновлено",
        ["settings.status.invalidHotkeys"] = "Виправ hotkeys перед збереженням",
        ["settings.status.openFolderFailed"] = "Не вдалося відкрити папку",
        ["settings.status.workflowCopy"] = "Сценарій: копіювати скріншот у буфер",
        ["settings.status.workflowEditor"] = "Сценарій: відкрити редактор після скріншоту",
        ["settings.status.workflowAi"] = "Сценарій: зберегти та запитати AI",
        ["settings.status.workflowSilent"] = "Сценарій: тихе збереження у файл",
        ["settings.status.workflowSaveHint"] = "{0}. Натисни «Зберегти», щоб застосувати",
        ["settings.validation.hotkeyFormat"] = "{0}: комбінація має бути на кшталт Ctrl+Shift+S або Ctrl+Alt+F1.",
        ["settings.validation.printScreen"] = "{0}: PrintScreen без модифікаторів не використовуємо, щоб не конфліктувати з Windows.",
        ["settings.validation.duplicate"] = "{0}: комбінація вже використовується для «{1}».",
        ["settings.default.promptTitle"] = "Новий prompt",
        ["settings.default.promptText"] = "Опиши, що потрібно зробити зі скріншотом.",
        ["settings.default.categoryName"] = "Нова категорія",
        ["settings.default.customCategoryName"] = "Користувацькі",
        ["settings.monitor.primarySuffix"] = " · основний",
        ["settings.monitor.fallback"] = "1: основний монітор",
        ["settings.hotkey.captureDefault.name"] = "Скріншот за замовчуванням",
        ["settings.hotkey.captureRegion.name"] = "Скріншот області",
        ["settings.hotkey.captureFullScreen.name"] = "Весь екран",
        ["settings.hotkey.captureActiveWindow.name"] = "Активне вікно",
        ["settings.hotkey.captureMonitor.name"] = "Монітор",
        ["settings.hotkey.captureDelayed.name"] = "Із затримкою",
        ["settings.hotkey.askAiForCurrentScreenshot.name"] = "AI для поточного скріншота",
        ["settings.hotkey.openMainWindow.name"] = "Відкрити головне вікно",
        ["settings.hotkey.openSettings.name"] = "Відкрити налаштування",
        ["settings.hotkey.captureDefault.description"] = "Запускає режим, вибраний у налаштуваннях скріншотів.",
        ["settings.hotkey.captureRegion.description"] = "Основний сценарій: виділення області та quick actions.",
        ["settings.hotkey.captureFullScreen.description"] = "Захоплення всіх екранів одним натисканням.",
        ["settings.hotkey.captureActiveWindow.description"] = "Знімок активного вікна без ручного виділення.",
        ["settings.hotkey.captureMonitor.description"] = "Захоплення монітора, вибраного в налаштуваннях.",
        ["settings.hotkey.captureDelayed.description"] = "Таймер перед скріншотом, корисно для меню і hover-станів.",
        ["settings.hotkey.askAiForCurrentScreenshot.description"] = "AI-запит тільки для вже створеного скріншота.",
        ["settings.hotkey.openMainWindow.description"] = "Повернення до dashboard.",
        ["settings.hotkey.openSettings.description"] = "Швидкий доступ до конфігурації.",
        ["settings.option.screenshot.region"] = "Область",
        ["settings.option.screenshot.fullScreen"] = "Весь екран",
        ["settings.option.screenshot.activeWindow"] = "Активне вікно",
        ["settings.option.screenshot.monitor"] = "Монітор",
        ["settings.option.screenshot.delayed"] = "Із затримкою",
        ["settings.option.theme.system"] = "Системна",
        ["settings.option.theme.light"] = "Світла",
        ["settings.option.theme.dark"] = "Темна",
        ["firstRun.title"] = "Перший запуск SmartScreen",
        ["firstRun.status"] = "Швидке налаштування SmartScreen",
        ["firstRun.behaviorTitle"] = "Базова поведінка",
        ["firstRun.behaviorDescription"] = "Програма працює з трею, а основне вікно відкривається для налаштувань.",
        ["firstRun.language"] = "Мова",
        ["firstRun.theme"] = "Тема",
        ["firstRun.screenshotsFolder"] = "Папка скріншотів",
        ["firstRun.afterCaptureTitle"] = "Після скріншоту",
        ["firstRun.afterCaptureDescription"] = "Це можна змінити пізніше в налаштуваннях.",
        ["firstRun.copyClipboard"] = "Копіювати в буфер",
        ["firstRun.showQuickMenu"] = "Показувати швидке меню",
        ["firstRun.openEditor"] = "Одразу відкривати редактор",
        ["firstRun.aiRouteTitle"] = "AI-маршрут",
        ["firstRun.aiRouteDescription"] = "Ключ можна додати після майстра в AI settings.",
        ["firstRun.hotkeys"] = "Default hotkeys: Ctrl+Shift+S, Ctrl+Shift+F, Ctrl+Shift+W, Ctrl+Shift+A",
        ["firstRun.start"] = "Почати",
        ["quick.ready"] = "Скріншот готовий",
        ["quick.saveFile"] = "Зберегти файл",
        ["quick.file"] = "Файл",
        ["quick.copyClipboard"] = "Копіювати в буфер",
        ["quick.clipboard"] = "Буфер",
        ["quick.editScreenshot"] = "Редагувати скріншот",
        ["quick.editShort"] = "Редаг.",
        ["quick.askAi"] = "Запитати AI",
        ["quick.openAiPanel"] = "Відкрити AI-панель",
        ["quick.request"] = "Запит",
        ["quick.openFolder"] = "Відкрити папку",
        ["quick.openScreenshotsFolder"] = "Відкрити папку скріншотів",
        ["quick.folder"] = "Папка",
        ["quick.closeOverlay"] = "Закрити overlay",
        ["quick.closeShort"] = "Закр.",
        ["quick.close"] = "Закрити",
        ["quick.copy"] = "Копія",
        ["editor.pen"] = "Олівець (P)",
        ["editor.highlighter"] = "Маркер (M)",
        ["editor.line"] = "Лінія (L)",
        ["editor.arrow"] = "Стрілка (A)",
        ["editor.rectangle"] = "Прямокутник (R)",
        ["editor.ellipse"] = "Еліпс (E)",
        ["editor.text"] = "Текст (T)",
        ["editor.crop"] = "Обрізання (C)",
        ["editor.blur"] = "Розмиття (B)",
        ["editor.pixelate"] = "Пікселізація (X)",
        ["editor.hidePanels"] = "Сховати панелі (H)",
        ["editor.showPanels"] = "Показати панелі (H)",
        ["editor.undo"] = "Скасувати (Ctrl+Z)",
        ["editor.redo"] = "Повторити (Ctrl+Y)",
        ["editor.clear"] = "Очистити позначки",
        ["editor.apply"] = "Застосувати (Ctrl+S або Enter)",
        ["editor.cancel"] = "Скасувати редактор (Esc)",
        ["editor.lineLabel"] = "Лінія",
        ["editor.textLabel"] = "Текст",
        ["editor.shapeFill"] = "Напівпрозора заливка фігур (F)",
        ["ai.panel"] = "AI-панель",
        ["ai.closePanel"] = "Закрити AI-панель",
        ["ai.action"] = "AI-дія",
        ["ai.sendRequest"] = "Надіслати AI-запит",
        ["ai.cancelRequest"] = "Скасувати AI-запит",
        ["ai.stop"] = "Стоп",
        ["ai.copyResponse"] = "Копіювати AI-відповідь",
        ["ai.saveResponse"] = "Зберегти AI-відповідь",
        ["quick.status.ready"] = "Готово",
        ["quick.status.chooseAction"] = "Вибери дію",
        ["quick.status.saved"] = "Збережено: {0}",
        ["quick.status.copiedClipboard"] = "Скопійовано в буфер",
        ["quick.status.editedCopied"] = "Відредаговано і скопійовано",
        ["quick.status.edited"] = "Відредаговано",
        ["quick.status.openFolderFailed"] = "Не вдалося відкрити папку",
        ["editor.status.applyFailed"] = "Не вдалося застосувати редагування",
        ["editor.status.copyFailed"] = "Не вдалося скопіювати скріншот",
        ["editor.status.saveFailed"] = "Не вдалося зберегти скріншот",
        ["editor.textPlaceholder"] = "Текст",
        ["ai.status.chooseAction"] = "Вибери AI-дію або зміни prompt",
        ["ai.status.panelClosed"] = "AI-панель закрито",
        ["ai.status.choosePrompt"] = "Вибери AI-дію або введи prompt",
        ["ai.status.analyzing"] = "AI аналізує скріншот...",
        ["ai.status.doneSeconds"] = "Готово за {0:N1} с",
        ["ai.status.error"] = "AI-помилка",
        ["ai.status.cancelled"] = "AI-запит скасовано",
        ["ai.status.requestFailed"] = "AI-запит завершився помилкою",
        ["ai.response.requestFailed"] = "Не вдалося виконати AI-запит. Деталі записано в logs/app.log.",
        ["ai.status.cancelling"] = "Скасування...",
        ["ai.status.responseCopied"] = "Відповідь скопійовано",
        ["ai.status.responseSaved"] = "Відповідь збережено: {0}",
        ["status.ready"] = "Готово до роботи"
    };

    public static IReadOnlyCollection<string> BuiltInKeys { get; } = BuiltInFallback.Keys.ToArray();

    public static event EventHandler? ResourcesChanged;

    public static async Task ApplyAsync(
        ILocalizationService localizationService,
        string cultureName,
        CancellationToken cancellationToken = default)
    {
        await localizationService.LoadAsync(cultureName, cancellationToken);
        Apply(localizationService.CurrentStrings);
    }

    public static void Apply(IReadOnlyDictionary<string, string> localizedStrings)
    {
        if (System.Windows.Application.Current?.Resources is null)
        {
            return;
        }

        foreach (var pair in BuiltInFallback)
        {
            System.Windows.Application.Current.Resources[ToResourceKey(pair.Key)] = pair.Value;
        }

        foreach (var pair in localizedStrings)
        {
            System.Windows.Application.Current.Resources[ToResourceKey(pair.Key)] = pair.Value;
        }

        ResourcesChanged?.Invoke(null, EventArgs.Empty);
    }

    public static string GetString(string key, string fallback)
    {
        var resourceKey = ToResourceKey(key);
        if (System.Windows.Application.Current?.Resources[resourceKey] is string resourceValue &&
            !string.IsNullOrWhiteSpace(resourceValue))
        {
            return resourceValue;
        }

        return BuiltInFallback.TryGetValue(key, out var builtInValue) ? builtInValue : fallback;
    }

    public static string ToResourceKey(string key) => $"{ResourcePrefix}{key}";
}
